name: Build

on:
  push:
    tags:
      - "*"

env:
  BASE_IMAGE_NAME: jellyfin-tizen-docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    strategy:
      matrix:
        platform:
          - linux/amd64
    #     - linux/arm64/v8
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ env.REPO }}:latest
            ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          build-args: |
            BUILD_NAME=${{ env.BASE_IMAGE_NAME }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ github.ref_name }}
